### ISSUE TITLE
Command is not send when scrolled in RunnerPane

### ISSUE THREAD

**Issue by jvanbaarsen** [christoomey/vim-tmux-runner#47]
When i've scrolled in my runner pane (for example to see a stacktrace in a test) and rerun `VtrSendCommand` the command is not executed on the runner pane. Instead I have to manually scroll all the way down (somehow the cursor went all the way to line 1 in the runner pane).

Is this expected behaviour? Or am I maybe doing something wrong?

**Comment by christoomey** [comment]
Hello @jvanbaarsen. This is expected behavior. Tmux has different key mappings in "copy mode" when you are scrolling back and you can't send commands over.

That said, you can use `q` to exit copy mode (run `tmux list-keys -t vi-copy` to see all the key bindings in that mode).

I also have the following mapping set up to easily send `q` from Vim:

``` vim
nnoremap <leader>q :VtrSendCommandToRunner q<cr>
```

Hope that helps. I'm going to close this issue now as I don't think there is anything to be done in the plugin, but please reopen or comment if you have additional questions.

**Comment by jvanbaarsen** [comment]
Thanks for explaining! Will try this in the morning
