### ISSUE TITLE
VtrAttachToPane Hangs

### ISSUE THREAD

**Issue by jShaf** [christoomey/vim-tmux-runner#75]
I tried vim-tmux-runner on this Centos 5 server however VtrAttachToPane would hang every time. I am running vim 7.2 and tmux 1.6. What is the minimum systems requirements?

**Comment by christoomey** [comment]
Hi @jShaf, sorry to hear about the trouble. I've not been particularly diligent with tracking tmux changes or testing with older versions, so I can't say exactly what version, but almost certainly the error is related to your tmux version as 1.6 is [from January 2012](https://github.com/tmux/tmux/blob/6995497e5b66e090f25e85fbb207f033f7790199/CHANGES#L597). Personally I'm running on tmux 2.3.

I've just pushed a quick change to the README to recommend 2.0+ for the tmux version. If you do happen to figure out anything more specific about version requirements, I'd love to hear them so I can update, but for now I'm going to close this issue as I believe the version is the issue here. Feel free to comment or re-open if you think I missed anything or if you're able to figure out anything specific about the version requirements.
