### ISSUE TITLE
SendLinesToRunner does not send partial lines

### ISSUE THREAD

**Issue by adamobeng** [christoomey/vim-tmux-runner#82]
At the moment, if a partial line is selected in visual mode, SendLinesToRunner sends the whole line.

Sometimes, it can be useful to send only the selected part(s) of line(s) to the runner, for example to check the value of a variable.

Could we modify SendLinesToRunner so that it sends partial lines if a partial line is selected (while still sending full lines if there is no visual selection)?

**Comment by christoomey** [comment]
@adamobeng Absolutely! This is high on my list of things to fix, hopefully in the near term.

Rather than fix SendLinesToRunner, my intention is to introduce a new operator for sending text such that it will work like other vim operations e.g. delete yank change. https://github.com/christoomey/vim-tmux-runner/issues/61 is intended to capture this.

I'm going to close this as I think #61 should cover this, but please feel free to comment or re-open if you think I missed something.
